
services:
  app:
    image: 192.168.1.1:5000/laravel-siak
    deploy:
      replicas: 1
      placement:
        preferences:
          - spread: node.role
        #constraints:
         # - node.role == worker or node.role == manager
    ports:
      - "9000:9000"
    volumes:
      - /mnt/web-siak2:/var/www
      - /mnt/web-siak2/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - "80:80"
    volumes:
      - /mnt/web-siak2:/var/www
      - /mnt/web-siak2/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/web-siak2/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
    attachable: true
